<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

app_countyhealth.healthdept by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in healthdept.php 

*/

class healthdept extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'app_countyhealth.healthdept';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'healthdept_url', //from from many
			'state', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'healthdept_name' => 'varchar',
		'county_name' => 'varchar',
		'population' => 'int',
		'state_id' => 'int',
		'fips_code' => 'varchar',
		'healthdept_url' => 'varchar',
		'wikipedia_url' => 'varchar',
		'county_url' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
			]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required form elements
    protected $non_nullable_fields = [
		'id',
		'healthdept_name',
		'county_name',
		'population',
		'state_id',
		'fips_code',
		'healthdept_url',
		'wikipedia_url',
		'county_url',
		'created_at',
		'updated_at',
			]; // End of nullable fields

    // Use Eloquent attributes array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $attributes = [
		'id' => null,
		'healthdept_name' => null,
		'county_name' => null,
		'population' => null,
		'state_id' => '7',
		'fips_code' => null,
		'healthdept_url' => null,
		'wikipedia_url' => null,
		'county_url' => null,
		'created_at' => 'current_timestamp()',
		'updated_at' => 'current_timestamp()',
			]; // End of attributes
        
		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

/**
*	get all the healthdept_url for this healthdept
*/
	public function healthdept_url(){
		return $this->hasMany('App\healthdept_url','healthdept_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

/**
*	get the single state for this healthdept
*/
	public function state(){
		return $this->belongsTo('App\state','state_id','id');
	}



//Originating SQL Schema
/*
CREATE TABLE `app_countyhealth`.`healthdept` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `healthdept_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `county_name` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `population` int(11) NOT NULL,
  `state_id` int(11) NOT NULL DEFAULT 7,
  `fips_code` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `healthdept_url` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `wikipedia_url` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `county_url` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `base_url` (`healthdept_url`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
*/


}//end of healthdept