<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

app_countyhealth.state by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in state.php 

*/

class state extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'app_countyhealth.state';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'healthdept', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'ssa_state_code' => 'varchar',
		'short_state' => 'varchar',
		'state_name' => 'varchar',
		'state_ucase' => 'varchar',
		'state_or_territory' => 'varchar',
		'population' => 'int',
		'is_known_good_state' => 'tinyint',
			]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required form elements
    protected $non_nullable_fields = [
		'id',
		'ssa_state_code',
		'state_ucase',
		'population',
		'is_known_good_state',
			]; // End of nullable fields

    // Use Eloquent attributes array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $attributes = [
		'id' => null,
		'ssa_state_code' => null,
		'short_state' => 'NULL',
		'state_name' => 'NULL',
		'state_ucase' => null,
		'state_or_territory' => 'NULL',
		'population' => null,
		'is_known_good_state' => '1',
			]; // End of attributes
        
		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

/**
*	get all the healthdept for this state
*/
	public function healthdept(){
		return $this->hasMany('App\healthdept','state_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `app_countyhealth`.`state` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ssa_state_code` varchar(3) NOT NULL,
  `short_state` varchar(3) DEFAULT NULL,
  `state_name` varchar(50) DEFAULT NULL,
  `state_ucase` varchar(255) NOT NULL,
  `state_or_territory` varchar(255) DEFAULT NULL,
  `population` int(11) NOT NULL,
  `is_known_good_state` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `short_state` (`short_state`),
  KEY `population` (`population`),
  KEY `ssa_state_code` (`ssa_state_code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='FROM the NPPES documentation'
*/


}//end of state